### ISSUE TITLE
'(Comonad m, Monad m) => Foldable (Stream m)' instead of 'Identity ~ m' constraint

### ISSUE THREAD

**Issue by Icelandjack** [snoyberg/foreach#1]
I don't know if this is useful for your purposes, but your [`Foldable (Stream f)`](https://github.com/snoyberg/foreach/blob/master/src/ForEach/Internal.hs#L22) could be given a `(Comonad m, Monad m)` constraint

```haskell
instance (Comonad m, Monad m) => Foldable (Stream m) where
  foldr f accum0 (Stream s0 next) =
    extract $ loop s0 accum0
    where
```

this lets you fold `Stream Identity` but also `Monoid m => Stream (m, )`, `Monoid m => Stream (m ->)`, `Stream NonEmpty`, `Alternative f => Stream (Cofree f)` ... (any type from [here](https://stackoverflow.com/questions/16551734/can-a-monad-be-a-comonad))

**Comment by snoyberg** [comment]
That's nifty, thank you! However, it's almost certainly not going to make it in here for two reasons:

1. I'd probably err towards keeping the dependency footprint on this package small
2. Initial performance testing showed that the `Foldable` instance performed poorly compared to alternative implementations of the same algorithm, so I will most likely be taking the instance out at some point to avoid accidentally slow code (see the comment here: 93cc2e1e284854c6e1b81ed928b72f23f95bc3bb).

**Comment by Icelandjack** [comment]
I see :+1:
